name: pokecard_dex
description: Una aplicación de lista infinita de Pokémon TCG.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  bloc: ^9.1.0
  bloc_concurrency: ^0.3.0
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  json_annotation: ^4.9.0
  meta: ^1.16.0
  stream_transform: ^2.1.1
  uuid: ^4.5.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/entrenador-pokemon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/entrenador-pokemon.png"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
